/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class HelloMyWorld {
    public static void main(String[] args) {
        HelloMyWorld text = new HelloMyWorld();
        System.out.println(text.helloMyWorld());

    }
    public String helloMyWorld (){

        return "Hello World" ;

    }
}
