/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

import org.testng.annotations.Test;

import static org.testng.AssertJUnit.assertEquals;

/**
 * Created by Hanna_Zhahala on 08.02.2017.
 */
public class HelloMyWorldTest {

    @Test
    public void shouldSayHelloWorld()
    {
        // given
        HelloMyWorld hw = new HelloMyWorld();
        // when
        String greeting = hw.helloMyWorld();
        // then
        assertEquals(greeting, "Hello World");
    }

}
